services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27777:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - ./mongo_data:/data/db

volumes:
  mongo_data: